FROM php:8.1.15-fpm-alpine3.17

RUN apk add --update linux-headers

RUN docker-php-ext-install pdo pdo_mysql

RUN apk add libzip-dev gcc make

RUN apk add --no-cache $PHPIZE_DEPS \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN pecl install redis \
    && docker-php-ext-enable redis

RUN docker-php-ext-install zip

RUN curl -sS https//getcomposer.org/installer | php -- install-dir=/usr/local/bin --filename=composer