version: "3.9"
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8081:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel
  
  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports:
      - "3310:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: db_docker
      # MYSQL_USER: user
      # DMYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_SERVICE_TAG:  dev
      MYSQL_SERVICE_NAME:  mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: laravel_php
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/html"
    networks:
      - laravel

  redis:
    image: redis:7.0.8-alpine
    container_name: laravel_redis
    command: redis-server --requirepass secret
    ports: 
      - "6379:6379"
    volumes:
      - "./redis:/data"
    networks:
      - laravel